// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx1VsQFszSZJRxn8zFQM2Gs91zETN832c',
    appId: '1:1086786709468:web:f4a6b155b16e048aab1119',
    messagingSenderId: '1086786709468',
    projectId: 'carpark-f0985',
    authDomain: 'carpark-f0985.firebaseapp.com',
    storageBucket: 'carpark-f0985.appspot.com',
    measurementId: 'G-Y0WV3776EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjRaQgp67eYlisAKlxgLZHhWv-oT0j9L4',
    appId: '1:1086786709468:android:3291ab61a2b50bf6ab1119',
    messagingSenderId: '1086786709468',
    projectId: 'carpark-f0985',
    storageBucket: 'carpark-f0985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKTIyn_hz2Lr3-F-iTRzSCcNA-_UV2wQ',
    appId: '1:1086786709468:ios:3ae1756ae88b5c1aab1119',
    messagingSenderId: '1086786709468',
    projectId: 'carpark-f0985',
    storageBucket: 'carpark-f0985.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKTIyn_hz2Lr3-F-iTRzSCcNA-_UV2wQ',
    appId: '1:1086786709468:ios:3ae1756ae88b5c1aab1119',
    messagingSenderId: '1086786709468',
    projectId: 'carpark-f0985',
    storageBucket: 'carpark-f0985.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx1VsQFszSZJRxn8zFQM2Gs91zETN832c',
    appId: '1:1086786709468:web:42c6dec475d2d085ab1119',
    messagingSenderId: '1086786709468',
    projectId: 'carpark-f0985',
    authDomain: 'carpark-f0985.firebaseapp.com',
    storageBucket: 'carpark-f0985.appspot.com',
    measurementId: 'G-WRPPR18ZRF',
  );
}
