// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6OOZ1Wz6MGQ-wFvAarnJcIgNqjSKYtSs',
    appId: '1:800285190243:web:4342e6c116ad75b49a7056',
    messagingSenderId: '800285190243',
    projectId: 'carparkingfour-3e0ec',
    authDomain: 'carparkingfour-3e0ec.firebaseapp.com',
    storageBucket: 'carparkingfour-3e0ec.appspot.com',
    measurementId: 'G-G3KYQZ68PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA-N4iYe7DxFarGCrmh8tADBdFb6GBKCI',
    appId: '1:800285190243:android:f3746f2ace64393a9a7056',
    messagingSenderId: '800285190243',
    projectId: 'carparkingfour-3e0ec',
    storageBucket: 'carparkingfour-3e0ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCorNoFVOa_4rOBLc0zdjP_PKAFmeBsdBk',
    appId: '1:800285190243:ios:83a81aca9aeb68169a7056',
    messagingSenderId: '800285190243',
    projectId: 'carparkingfour-3e0ec',
    storageBucket: 'carparkingfour-3e0ec.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCorNoFVOa_4rOBLc0zdjP_PKAFmeBsdBk',
    appId: '1:800285190243:ios:83a81aca9aeb68169a7056',
    messagingSenderId: '800285190243',
    projectId: 'carparkingfour-3e0ec',
    storageBucket: 'carparkingfour-3e0ec.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6OOZ1Wz6MGQ-wFvAarnJcIgNqjSKYtSs',
    appId: '1:800285190243:web:14b2f485e4687f879a7056',
    messagingSenderId: '800285190243',
    projectId: 'carparkingfour-3e0ec',
    authDomain: 'carparkingfour-3e0ec.firebaseapp.com',
    storageBucket: 'carparkingfour-3e0ec.appspot.com',
    measurementId: 'G-56SSHSGB71',
  );
}
