// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCULk4cDsVFWx_LKVEKOy7_v4lnZpInfk4',
    appId: '1:382387121502:web:61cfd060c168d61a1333cf',
    messagingSenderId: '382387121502',
    projectId: 'carparkingthree-b893f',
    authDomain: 'carparkingthree-b893f.firebaseapp.com',
    storageBucket: 'carparkingthree-b893f.appspot.com',
    measurementId: 'G-F3WWEKBDDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZKtwp179gIzBIEE-ZYlL10ne6Uj2tCjw',
    appId: '1:382387121502:android:0a9c8cfbcabc16e11333cf',
    messagingSenderId: '382387121502',
    projectId: 'carparkingthree-b893f',
    storageBucket: 'carparkingthree-b893f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC32dd_Gr9Txny542Bf-TI8L81ViLMmJ2o',
    appId: '1:382387121502:ios:9af13158c963d1431333cf',
    messagingSenderId: '382387121502',
    projectId: 'carparkingthree-b893f',
    storageBucket: 'carparkingthree-b893f.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC32dd_Gr9Txny542Bf-TI8L81ViLMmJ2o',
    appId: '1:382387121502:ios:9af13158c963d1431333cf',
    messagingSenderId: '382387121502',
    projectId: 'carparkingthree-b893f',
    storageBucket: 'carparkingthree-b893f.appspot.com',
    iosBundleId: 'com.example.carparking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCULk4cDsVFWx_LKVEKOy7_v4lnZpInfk4',
    appId: '1:382387121502:web:82318d0cd9077ffb1333cf',
    messagingSenderId: '382387121502',
    projectId: 'carparkingthree-b893f',
    authDomain: 'carparkingthree-b893f.firebaseapp.com',
    storageBucket: 'carparkingthree-b893f.appspot.com',
    measurementId: 'G-DSNL6034TY',
  );
}
